# Generated by Django 4.1.5 on 2023-01-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_category_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='course_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
